name: Deploy to EKS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 941824419453.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build, tag, and push Docker image
        run: |
          docker build -t node-app .
          docker tag node-app:latest 941824419453.dkr.ecr.ap-south-1.amazonaws.com/node-app:latest
          docker push 941824419453.dkr.ecr.ap-south-1.amazonaws.com/node-app:latest

      - name: Deploy to EKS
        run: |
          aws eks update-kubeconfig --name node-fargate-cluster --region ap-south-1
          kubectl rollout restart deployment node-app
